######################################################################
# Automatically generated by qmake (3.0) K aug. 18 19:54:09 2015
######################################################################

TEMPLATE = app
TARGET = ZSFEdit
QT += widgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp mainwindow.cpp \
    wave.cpp
HEADERS += mainwindow.h \
    wave.h

RESOURCES += \
    rc.qrc
